function EFFECT:Init(data)
	local pos = data:GetOrigin()
	local em = ParticleEmitter(pos)
	pos = pos + Vector(0,0,18)
	local part = em:Add("pikmin/shock",pos)
	part:SetColor(0,208,255,255)
	part:SetVelocity(Vector(0,0,0))
	part:SetDieTime(0.5)
	part:SetLifeTime(0)
	part:SetStartSize(100)
	part:SetEndSize(0)
	part:SetStartAlpha(255)
	part:SetEndAlpha(0)
	part:SetCollide(false)
	part:SetGravity(Vector(0,0,0))
	part:SetAngleVelocity(Angle(0,0,0))
	part:SetLighting(false)
	local part = em:Add("pikmin/death_shock",pos)
	part:SetColor(255,255,255,255)
	part:SetVelocity(Vector(0,0,0))
	part:SetDieTime(0.1)
	part:SetLifeTime(0)
	part:SetStartSize(20)
	part:SetEndSize(15)
	part:SetStartAlpha(255)
	part:SetEndAlpha(255)
	part:SetCollide(false)
	part:SetGravity(Vector(0,0,0))
	part:SetAngleVelocity(Angle(0,0,0))
	part:SetLighting(false)
	em:Finish()
end

function EFFECT:Think()
end


function EFFECT:Render()
end